"""Add ShortUrl

Revision ID: 8ed4f9e7c1d3
Revises: e94be5138a34
Create Date: 2024-10-18 15:56:24.822510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed4f9e7c1d3'
down_revision: Union[str, None] = 'e94be5138a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shorturl',
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('short', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shorturl')
    # ### end Alembic commands ###
